name: Mask_RCNN
dependencies:
  - cudatoolkit=10.0
  - cudnn=7.6.5
  - python=3.6
  - pip
  - setuptools<45.0.0
  - pyinstaller
  - swig
  - pip:
    - numpy
    - scipy
    - scikit-image
    - imgaug
    - h5py==2.10.0
#    - tensorflow==1.15
    - tensorflow-gpu==1.15
    - keras==2.1.6
